ID = "ID"
PW = "PW"
MAIL = "MAIL"
PHONE = "PHONE"

BANK_ACNT = "BANK_ACNT"
BANK_PW = "BANK_PW"
BANK_LOG = "BANK_LOG"

MEMO_DATE = "DATE"
MEMO_TEXT = "TEXT"

TODO_TEXT = "TEXT"
REGISTER_DAY = "REGISTER"
EXPIRED_DAY = "EXPIRED"
REMAINING = "REMAINING"
SUCCESS = "SUCCESS"

# print(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
